import { PT_Serif } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const ptSerif = PT_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ptSerif.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sora">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
